# Generated by Django 5.2.6 on 2025-09-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_usuario_email_alter_usuario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('A', 'A fazer'), ('F', 'Fazendo'), ('P', 'Pronto')], default='A', max_length=20),
        ),
    ]
