# Generated by Django 5.2.6 on 2025-09-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_tarefas_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='data',
        ),
    ]
