# Generated by Django 5.2.6 on 2025-09-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_tarefas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
